stm32_control_node:
  ros__parameters:
    frequency: 50.0
    odom_name: odom
    base_link_name: lidar
    use_pose_topic_for_current_pose: true
    current_pose_topic_name: /glim_ros/pose_corrected
    goal_pose_topic_name: /target
    stag_center_topic_name: /stag_center
    stag_detected_topic_name: /stag_detected
    arm_angles_topic_name: /arm_angles
    yolo_offsets_topic_name: /yolo_detection_offsets
    stm32_read_topic: stm32/read
    stm32_write_topic: stm32/write