bt_executor:
  ros__parameters:
    action_name: bt_execution
    tick_frequency: 50
    plugins:
      - tf_listen_bt/lib
      - pose_est_bt/lib
      - camera_stag_bt/lib
      - yolo_spearhead_see_bt/lib
      - move_to_position_bt/lib
    behavior_trees:
      - src/r2_decision/behavior_trees
