<?xml version="1.0"?>
<package format="3">
  <name>robot_arm_bt</name>
  <version>0.0.1</version>
  <description>BehaviorTree.CPP ROS2 plugin nodes for robot_arm IK service.</description>
  <maintainer email="you@example.com">your_name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>behaviortree_ros2</depend>
  <depend>pose_interface</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>